<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'de4be7a1990b1f5c9fefcb6ef20967a2',
  'API_BASE_URL' => 'http://localhost:8443/',
);
