<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'de4be7a1990b1f5c9fefcb6ef20967a2',
  'API_BASE_URL' => 'https://localhost:8443/',
);
